// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/string.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strings []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_string_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_string_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_string_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptRequest) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

type EncryptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encrypted bool     `protobuf:"varint,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Strings   []string `protobuf:"bytes,2,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *EncryptReply) Reset() {
	*x = EncryptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_string_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptReply) ProtoMessage() {}

func (x *EncryptReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_string_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptReply.ProtoReflect.Descriptor instead.
func (*EncryptReply) Descriptor() ([]byte, []int) {
	return file_proto_string_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptReply) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *EncryptReply) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

var File_proto_string_proto protoreflect.FileDescriptor

var file_proto_string_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x46, 0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x32,
	0x4a, 0x0a, 0x09, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x0d,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_string_proto_rawDescOnce sync.Once
	file_proto_string_proto_rawDescData = file_proto_string_proto_rawDesc
)

func file_proto_string_proto_rawDescGZIP() []byte {
	file_proto_string_proto_rawDescOnce.Do(func() {
		file_proto_string_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_string_proto_rawDescData)
	})
	return file_proto_string_proto_rawDescData
}

var file_proto_string_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_string_proto_goTypes = []interface{}{
	(*EncryptRequest)(nil), // 0: proto.EncryptRequest
	(*EncryptReply)(nil),   // 1: proto.EncryptReply
}
var file_proto_string_proto_depIdxs = []int32{
	0, // 0: proto.Encryptor.EncryptString:input_type -> proto.EncryptRequest
	1, // 1: proto.Encryptor.EncryptString:output_type -> proto.EncryptReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_string_proto_init() }
func file_proto_string_proto_init() {
	if File_proto_string_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_string_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_string_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_string_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_string_proto_goTypes,
		DependencyIndexes: file_proto_string_proto_depIdxs,
		MessageInfos:      file_proto_string_proto_msgTypes,
	}.Build()
	File_proto_string_proto = out.File
	file_proto_string_proto_rawDesc = nil
	file_proto_string_proto_goTypes = nil
	file_proto_string_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EncryptorClient is the client API for Encryptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EncryptorClient interface {
	EncryptString(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptReply, error)
}

type encryptorClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptorClient(cc grpc.ClientConnInterface) EncryptorClient {
	return &encryptorClient{cc}
}

func (c *encryptorClient) EncryptString(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptReply, error) {
	out := new(EncryptReply)
	err := c.cc.Invoke(ctx, "/proto.Encryptor/EncryptString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptorServer is the server API for Encryptor service.
type EncryptorServer interface {
	EncryptString(context.Context, *EncryptRequest) (*EncryptReply, error)
}

// UnimplementedEncryptorServer can be embedded to have forward compatible implementations.
type UnimplementedEncryptorServer struct {
}

func (*UnimplementedEncryptorServer) EncryptString(context.Context, *EncryptRequest) (*EncryptReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptString not implemented")
}

func RegisterEncryptorServer(s *grpc.Server, srv EncryptorServer) {
	s.RegisterService(&_Encryptor_serviceDesc, srv)
}

func _Encryptor_EncryptString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptorServer).EncryptString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Encryptor/EncryptString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptorServer).EncryptString(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Encryptor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Encryptor",
	HandlerType: (*EncryptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptString",
			Handler:    _Encryptor_EncryptString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/string.proto",
}
